#!/bin/bash

# create a big file for chunking 

FILE=merkelfile.txt
STRING=""
for i in {1..10000}; do
	STRING=${STRING}"line $i"
done

echo "$STRING" > "$FILE"
MERKELFILE_SIZE=$( du -h $FILE ) 
echo "$MERKELFILE_SIZE"
